spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3500/ecommerce?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjd0322189
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: 9999
